site_name: MorfoBlocos Digital
site_description: Documentação do projeto MorfoBlocos Digital - Engenharia de Software
site_author: Equipe G4

theme:
  name: material
  palette:
    # Opção de alternar entre tema claro e escuro
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Mudar para modo escuro 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

nav:
  - 'Unidade II':
    - 'Início': 'v1/index.md'
    - 'Reuniões': 'v1/reunioes.md'
    - 'Visão do Produto': 'v1/visao_produto.md'
  - 'Unidade III':
    - 'Início': 'v2/index.md'
    - 'Sprints':
      - 'Sprint 1': 'v2/sprints/sprint1.md'
      - 'Sprint 2': 'v2/sprints/sprint2.md'
      - 'Sprint 3': 'v2/sprints/sprint3.md'      
      - 'Sprint 4': 'v2/sprints/sprint4.md'      