site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01--MorfoBlocosDigital/
site_name: MorfoBlocos Digital
site_description: Documentação do projeto MorfoBlocos Digital - Engenharia de Software
site_author: Equipe G4

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables

theme:
  name: material

  language: pt-BR

  palette:
    - scheme: default
      primary: blue
      accent: red

      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: blue
      accent: yellow

      toggle:
        icon: material/weather-sunny
        name: Modo claro

  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - toc.follow
  - content.code.copy
  - search.highlight

home:
  hide:
  - navigation

nav:
  - 'Início': 'index.md'

  - 'Unidade II':
    - 'Início': 'v1/index.md'
    - 'Reuniões': 'v1/reunioes.md'
    - 'Visão do Produto': 'v1/visao_produto.md'
  - 'Unidade III':
    - 'Início': 'v2/index.md'
    - 'Visão do Produto': 
      - 'Cenário Atual do Cliente e do Negócio': v2/visao-produto/cenario-atual.md
      - 'Solução Proposta': 'v2/visao-produto/solucao-proposta.md'
      - 'Intervenção Social': 'v2/visao-produto/intervencao-social.md'
      - 'Estratégias de Engenharia de Software': 'v2/visao-produto/estrategias-esw.md'
      - 'Engenharia de Requisitos': 'v2/visao-produto/eng-requisitos.md'
      - 'Cronograma': 'v2/visao-produto/cronograma.md'
      - 'Interação entre a Equipe e Cliente': 'v2/visao-produto/interacao-eqp-cliente.md'
      - 'Requisitos de Software': 'v2/visao-produto/requisitos.md'
      - 'Definition of Ready (DoR) e Definition of Done (DoD)': 'v2/visao-produto/dor-dod.md'
      - 'Backlog': 'v2/visao-produto/backlog.md'

      - 'Lições Aprendidas': 'v2/visao-produto/licoes-aprendidas.md'
    - 'Sprints':
      - 'Sprint 1': 'v2/sprints/sprint1.md'
      - 'Sprint 2': 'v2/sprints/sprint2.md'
      - 'Sprint 3': 'v2/sprints/sprint3.md'      
      - 'Sprint 4': 'v2/sprints/sprint4.md'   
    - 'Reuniões': 'v2/reunioes.md'
    - 'Status do projeto': 'v2/status-projeto.md'
  - 'Unidade IV':
    - 'Início': 'v3/index.md'
    - 'Planejamento e Organização': 'v3/planejamento.md'
    - 'Visão do Produto': 
      - 'Cenário Atual do Cliente e do Negócio': v3/visao-produto/cenario-atual.md
      - 'Solução Proposta': 'v3/visao-produto/solucao-proposta.md'
      - 'Intervenção Social': 'v3/visao-produto/intervencao-social.md'
      - 'Estratégias de Engenharia de Software': 'v3/visao-produto/estrategias-esw.md'
      - 'Engenharia de Requisitos': 'v3/visao-produto/eng-requisitos.md'
      - 'Cronograma': 'v3/visao-produto/cronograma.md'
      - 'Interação entre a Equipe e Cliente': 'v3/visao-produto/interacao-eqp-cliente.md'
      - 'Requisitos de Software': 'v3/visao-produto/requisitos.md'
      - 'Definition of Ready (DoR) e Definition of Done (DoD)': 'v3/visao-produto/dor-dod.md'
      - 'Backlog': 'v3/visao-produto/backlog.md'
      - 'User Stories': 'v3/userstories.md'
      - 'Lições Aprendidas': 'v3/visao-produto/licoes-aprendidas.md'
    - 'Sprints':
      - 'Sprint 1': 'v3/sprints/sprint1.md'
      - 'Sprint 2': 'v3/sprints/sprint2.md'
      - 'Sprint 3': 'v3/sprints/sprint3.md'      
      - 'Sprint 4': 'v3/sprints/sprint4.md'   
      - 'Sprint 5': 'v3/sprints/sprint5.md'
      - 'Sprint 6': 'v3/sprints/sprint6.md'
    - 'Reuniões':
      - 'Monitorias': 'v3/reunioes/monitorias.md'
      - 'Cliente': 'v3/reunioes/cliente.md'
      - 'Entrega das Unidades': 'v3/reunioes/videos-unidades.md'
    

copyright: |
  © 2026 Equipe G4 • Engenharia de Software - FGA/UnB