# Generated by Django 6.0.5 on 2026-06-01 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Morfema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grafia", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PREFIXO", "Prefixo"),
                            ("RADICAL", "Radical"),
                            ("SUFIXO", "Sufixo"),
                            ("VOGAL_TEMATICA", "Vogal Temática"),
                            ("DESINENCIA", "Desinência"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PalavraMorfema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "morfema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickstart.morfema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PalavraValida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palavra", models.CharField(max_length=100, unique=True)),
                (
                    "processo_morfologico",
                    models.CharField(
                        choices=[
                            ("PREFIXAL", "Derivação Prefixal"),
                            ("SUFIXAL", "Derivação Sufixal"),
                            ("PREFIXAL_SUFIXAL", "Derivação Prefixal e Sufixal"),
                            ("PARASSINTETICA", "Derivação Parassintética"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tentativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palavra_montada", models.CharField(max_length=100)),
                ("correta", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "palavra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickstart.palavravalida",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TentativaMorfema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "morfema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickstart.morfema",
                    ),
                ),
                (
                    "tentativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="morfemas_usados",
                        to="quickstart.tentativa",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.AddField(
            model_name="palavramorfema",
            name="palavra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="morfemas",
                to="quickstart.palavravalida",
            ),
        ),
    ]
