# Generated by Django 6.0.5 on 2026-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Morfema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("prefixo", "Prefixo"),
                            ("radical", "Radical"),
                            ("sufixo", "Sufixo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cor", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PalavraValida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=100, unique=True)),
                ("processo_morfologico", models.CharField(max_length=200)),
            ],
        ),
    ]
