name: CI MorfoBlocos Django

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # 📌 A MÁGICA ESTÁ AQUI: Avisa o GitHub para rodar tudo dentro da pasta backend
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # 📌 Mudei de 3.11 para 3.12 aqui!
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Rodar Testes Automatizados (TDD)
      env:
        SECRET_KEY: 'chave-falsa-so-para-o-robo-testar'
        DEBUG: 'True'
      run: |
        python manage.py test